plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':assist-core')
    implementation project(':assist-registration')
    implementation project(':assist-identity')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jersey'
    implementation 'org.glassfish.jersey.media:jersey-media-multipart'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.liquibase:liquibase-core'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
    implementation 'io.swagger.core.v3:swagger-jaxrs2-jakarta:2.2.28'

    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'com.h2database:h2'
}

bootRun {
    systemProperty 'spring.profiles.active', System.getProperty('spring.profiles.active', 'dev')
}
