dependencies {
    implementation project(':assist-core')
    implementation project(':assist-registration')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jersey'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'io.swagger.core.v3:swagger-annotations-jakarta:2.2.28'
}
