server.port=8443
server.servlet.context-path=/assist-provider
server.ssl.enabled=false

spring.application.name=assist-provider

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=registration
spring.jpa.show-sql=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/ns3_assist
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.url=/api/openapi.json
springdoc.swagger-ui.disable-swagger-default-url=true

management.endpoints.web.exposure.include=health,info
