dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework:spring-tx'
    implementation 'org.springframework:spring-aop'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'jakarta.validation:jakarta.validation-api'
}
